version: "3"
 
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: dal-datascience-postgres
    container_name: dal-postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword1234
      - PGPASSWORD=mysecretpassword1234
      - POSTGRES_DB=dsdojo_db
      - DATABASE_HOST=localhost
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
      - $PWD/docker/work/data:/tmp/data

  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    image: dal-datascience-notebook
    container_name: dal-notebook
    ports:
      - "8889:8888"
    environment:
      - PG_PORT=5432
      - PG_USER=padawan
      - PG_PASSWORD=padawan12345
      - PG_DATABASE=dsdojo_db
      - JUPYTER_ENABLE_LAB=yes
    links:
      - db
    volumes:
      - $PWD/docker/work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
